services:
    postgres:
        container_name: postgres-db
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          PGDATA: /var/lib/postgresql/data
        volumes:
          - postgres:/var/lib/postgresql/data
        ports:
          - 5432:5432
        networks:
          - microservices-net
        restart: unless-stopped


    mail-dev:
      container_name: mail-e_trade
      image: maildev/maildev
      ports:
        - "1080:1080"
        - "1025:1025"

    keycloak:
      container_name: keycloak-e_trade
      image: quay.io/keycloak/keycloak:26.1.2
      ports:
        - "8080:8080"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      networks:
        - microservices-net
      command:
        - "start-dev"

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
